### ISSUE TITLE
potentially pointless netplan.stamp

### ISSUE THREAD

**Issue by xnox** [canonical/netplan.io#246]
## Summary

netplan generator creates netplan.stamp because of "Write a stamp file into the generator dir to avoid regenerating the configuration on each daemon-reload."

I am guessing daemon-reload, here means `systemctl daemon-reload`. However, systemd removes the generator directory, including netplan.stamp, when doing daemon-reload, and calls to regenerate all the netplan units.

which imho is the right thing to do, in case systemd-networkd is later restarted.

It leads me to believe that writing and checking for netplan.stamp file is actually pointless, throughout. And has been the case since introduction. Or is it actually in use anywhere? I.e. does any external users need it? tests or cloud-init?

**Comment by sowasred2012** [comment]
Hi there, thanks for reporting - this is the repo for the netplan.io site, bugs for netplan itself should be filed here: https://launchpad.net/netplan
