### ISSUE TITLE
FAQ should give better instructions for deconfiguring an interface

### ISSUE THREAD

**Issue by PenelopeFudd** [canonical/netplan.io#268]
## Summary
I edited my netplan configuration by deleting some interfaces/bridges/vlans and then ran `netplan apply`, and was irked that the they were still there afterwards.

* The [FAQ](https://netplan.io/faq#deconfigure-an-interface) says:
>  To remove addresses manually, a user can run `ip address del <address> dev <interface>`.
* The [man page](https://manpages.ubuntu.com/manpages/jammy/man8/netplan-apply.8.html#known%20issues) says:
```
mkdir  -p  /tmp/netplan_state_backup/etc  &&  cp  -r  /etc/netplan /tmp/netplan_state_backup/etc/   

netplan      apply      –state
       /tmp/netplan_state_backup
```
Note: The man page shows `–state`, which should really be `--state`, since Unicode long-dashes aren't recognized by most CLI tools.

## Process

1. Create an interface in a separate file in /etc/netplan
2. Run `netplan apply`
3. See the new interface with `ip address`
4. Delete the separate file in /etc/netplan
5. Run `netplan apply`
6. Check that the interface was deleted with `ip address`
7. Try the procedure in the FAQ -- meh, that looks hard
8. Try the procedure in the man page known issues section

## Current and expected result

* The interface was not deleted in step 6
* Step 7 looked hard, I skipped it
* Step 8 didn't delete the interface and didn't print an error

Changing the final commands to 
```
mkdir  -p  /tmp/netplan_state_backup/etc  &&  cp  -r  /etc/netplan /tmp/netplan_state_backup/etc/   

sudo rm /etc/netplan/interface-to-delete.yaml

sudo netplan apply --state /tmp/netplan_state_backup
``` 
worked, though.

Could you change the FAQ and man page to give the right commands?

Netplan has a bad reputation about not printing error messages and requiring a reboot to delete interfaces, this should help.

**Comment by carkod** [comment]
@slyon can you take a look see if we need to apply any changes to the FAQ page?

**Comment by slyon** [comment]
Yes, I think that's a pretty good suggestions, see https://github.com/canonical/netplan.io/pull/286
