### ISSUE TITLE
Please implement routing-policy support for IncomingInterface in networkd?

### ISSUE THREAD

**Issue by elmaimbo** [canonical/netplan.io#284]
## Summary

According to the netplan manual page, routing-policy rules can match using the following options (when using networkd back-end): from, to, mark, type-of-service. These options map to networkd RoutingPolicyRule options: From, To, FirewallMark, TypeOfService (respectively).

There is currently no option in netplan that maps to IncomingInterface option in networkd? (This option allows traffic to match based on which interface that the packet was received on.)

There are of course many other networkd capabilities that could be added to netplan -- which would also be great -- however I believe that IncomingInterface is the most vital feature that is missing currently.

## Current and expected result

Currently there is no option documented in the netplan manual page to define a rule that maps to networkd's IncomingInterface option. Might I suggest that the new option should be named "iif" (short for incoming interface), as this terminology would be consistent with the "ip rule" command's syntax and output?

**Comment by carkod** [comment]
Thank you for suggesting this. Can you provide the link of the page?

You may have better luck filing this in the [netplan](https://bugs.launchpad.net/netplan) , as this is the website of https://netplan.io/, and it seems the documentation is an external site.

**Comment by elmaimbo** [comment]
Sorry I didn't realise that netplan and netplan.io were different projects. I've added the information above to an existing bug report in the netplan project: https://bugs.launchpad.net/netplan/+bug/1798417
